
let introduction_text = `<p>We have passed from one animal to the other, from the mole to the serpent, in the system under which we live, but also in our manner of living and in our relations with others. The disciplinary man was a discontinuous producer of energy, but the man of control is undulatory, in orbit, in a continuous network. Everywhere surfing has already replaced the older sports.</p>
<p style="text-align: left;">&ndash; Gilles Deleuze</p>
<p><br>&ldquo;Why Are Young People Pretending to Love Work?&rdquo; asks Erin Griffith for <em>The New York Times</em>, pointing to the curious development of American millennials, who, despite their bubbling discontent for corporations and flirts with anti-capitalist rhetoric, nevertheless partake in a performative workaholism that dresses zeal, overexertion and social competitiveness in the appearances of passion, creativity and engagement.<sup id="link_1"><a href="#ref_1">1</a></sup></p>
<p><br>The new professional workplace, replete with high-minded messaging and amenities catering to every need &ndash; nursing, feeding and spiritually guiding their employees &ndash; has spread from the tech startups of Silicon Valley to white-collar organizations globally. With access to medical facilities, gyms, laundromats, shops, eateries, bars and supermarkets, with work appearing more free and laidback, and with life&rsquo;s conveniences at one&rsquo;s fingertips&ndash; why would you ever leave?</p>
<p><br>The new corporate culture mantra is expressed in the slogan of American shared workspace company WeWork, who implores its tenants (called &lsquo;members&rsquo;) to &ldquo;make a life, not just a living.&rdquo; WeWork landed this year in Johannesburg&rsquo;s still-growing decentralized CBDs; Sandton and Rosebank. These two areas continue to witness surges in property development as many companies complete their migration from the old Johannesburg into its new financial centres, now reinventing themselves in the 4th Industrial Revolution geist as &lsquo;smart cities.&rsquo;</p>
<p><br>HSBC, one of the world&rsquo;s largest financial services providers, decided this year to lease 1,135 desks from a WeWork in London. Citigroup and Deutsche Bank also house some of their operations in WeWork buildings, and in Johannesburg, Standard Bank and NASPERS are joining this cohort of big name tenants. Given the rise of precarious, short-term work, the appeal of WeWork to freelancers is obvious &ndash; but why are big multinational corporations similarly charmed by WeWork, or at the very least to re-style themselves in its fashion? A marketing pitch for a Manhattan based WeWork gives a clue: &ldquo;Your old office might have had a coffee pot,&rdquo; it reads, &ldquo;but ours has a microroasted coffee bar and fresh fruit water.&rdquo; It&rsquo;s hard to imagine that premium roasted beans revolutionize the work experience. In the new world of work, work appears to be about everything but work.</p>
<p><br>Although what was the old way of work? In capitalism, the evolution of the workplace is the story of the development of its managerial techniques, driven by its most basic feature &ndash; the exploitation of workers in the pursuit of profit. Richard C. Edwards describes how control is the animating principle behind changes to the workplace, where, &ldquo;The labor process becomes an arena of class conflict and the workplace becomes a contested terrain. Faced with chronic resistance to their efforts to compel production, employers over the years have attempted to resolve the matter by reorganizing, indeed revolutionizing, the labor process itself. Their goal remains profits; their strategies aim at establishing structures of control at work.&rdquo;<sup id="link_2"><a href="#ref_2">2</a></sup><br>Labor coercion is endemic to capitalism, and the truth is that there is no qualitative uniqueness to recent developments.&nbsp;</p>
<p><br><a href="#link_1"><sup id="ref_1">1</sup></a> Erin Griffith, &quot;Why Are Young People Pretending to Love Work?,&rdquo; The New York Times, January 26, 2019, <a href="https://www.nytimes.com/2019/01/26/business/against-hustle-culture-rise-and-grind-tgim.html" target="_blank">https://www.nytimes.com/2019/01/26/business/against-hustle-culture-rise-and-grind-tgim.html</a>.</p>
<p><br><a href="#link_2"><sup id="ref_2">2</sup></a>Richard Edwards, Contested Terrain: The Transformation of the Workplace in the Twentieth Century (New York: Basic Books, 1979), 16.</p>`



let moles_text = `<p>The early phase of industrial work was monitored by a supervisor or foreman wielding the threat of force, a hangover of feudal and colonial relations which Michel Foucault described as &ldquo;societies of sovereignty,&rdquo; with powers to harshly punish.<sup id="link_3"><a href="#ref_3">3</a></sup> For example, South Africa&rsquo;s  early, racially fraught mineworker struggles beginning in 1883 Kimberly resisting strip and search rules and culminating in the 1922 Rand Rebellion typifies this early period of brutal control, met with fierce resistance followed by violent repression &ndash; &ldquo;This kind of working subject has no rights, it is exploited like a slave, without (public) protection; the worker completely depends on the will of the sovereign that can hire and fire him at any time.&rdquo;<sup id="link_4"><a href="#ref_4">4</a></sup> In the transition to Fordist capitalism this system would eventually collapse, paving the way for &lsquo;softer&rsquo; disciplinary techniques since, &ldquo;Bosses were petty tyrants, supervisors prone to arbitrary authoritarianism, and the visible presence of line managers made them easy targets for retribution.&rdquo;<sup id="link_5"><a href="#ref_5">5</a></sup></p>
<p><br>Following this, the regime of workplace control was revised to be mechanistic and impersonal, organized around the model of the &lsquo;factory&rsquo; within industrial production, as well as around the &lsquo;office&rsquo; of public administration.<sup id="link_6"><a href="#ref_6">6</a></sup> With the birth of the modern liberal state, was the shift to, in Foucault&rsquo;s terms, a &lsquo;disciplinary society&rsquo; that employed rigid and hierarchical methods of control exercised in the enclosed spaces of factory, office, school or prison, and regulated by normalization and standardization.<sup id="link_7"><a href="#ref_7">7</a></sup> Control was imposed through an indirect disciplinary architecture designed to produce self-disciplining subjects that modelled their behaviour according to well-established rules and regulations, yet wielded by an invisible power: &ldquo;[the individual] who is subjected to a field of visibility, and who knows it, assumes responsibility for the constraints of power; he makes them play spontaneously upon himself; he inscribes in himself the power relation in which he simultaneously plays both roles; he becomes the principle of his own subjection.&rdquo;<sup id="link_8"><a href="#ref_8">8</a></sup></p>
<p><br>As an ideology of cool, rational control, Fordist-Bureaucracy employed methods of production standardization and surveillance to maximize efficiency and stability.<sup id="link_9"><a href="#ref_9">9</a></sup> Governed by a strict division of labour kind and the specialization of labour roles, workers are required to do calculable tasks specific to their competency and place in the workplace hierarchy, wherein, &ldquo;Fixed blueprints and linear time tables produced a stable rhythm of the work process as they clearly defined what had to be done, when and by whom.&rdquo;<sup id="link_10"><a href="#ref_10">10</a></sup> Work was straightforward, albeit monotonous&ndash; the worker was a passive recipient of formalized tasks and commands, to be completed during a routinized timetable where &lsquo;start&rsquo; and &lsquo;finish&rsquo; are clear, with their productivity determined by measurable criteria and enforced by a Panopticon model of surveillance. In return for their<sup id="link_11"><a href="#ref_11">11</a></sup> labour, this &lsquo;man of exchange&rsquo; was afforded secure employment in the firm, and if ambitious, in exchange for their obedience and loyalty, the &lsquo;organizational man&rsquo; who successfully exhibited their conformity with the firm&rsquo;s norms and standards was promised organizational ascendancy.<sup id="link_12"><a href="#ref_12">12</a></sup></p>
<p>Weber encapsulates the ethos of Fordist-Bureaucracy thus: &ldquo;The more bureaucracy is dehumanized, the more completely it succeeds in eliminating from official business love, hatred, and all purely personal, irrational and emotional elements which escape calculation. This is the specific nature of bureaucracy and it is appraised as its special virtue.&rdquo;<sup id="link_13"><a href="#ref_13">13</a></sup> On the one hand, this leads to the worker becoming thoroughly alienated from their work, where as Erich Fromm explains, &ldquo;[The worker] is put in a certain place, has to carry out a certain task, but does not participate in the organization or management of the work. He is not interested, nor does he know why one produces this, instead of another commodity&mdash;what relation it has to the needs of society as a whole.&rdquo;<sup id="link_14"><a href="#ref_14">14</a></sup>On the other hand, the bureaucratic workplace devoid of autonomy expels &lsquo;life&rsquo; and emotion from it such that the physicality of the workplace came to symbolize a space for work and work only, with the worker&rsquo;s life and time being their own once clocked out. It is therefore clear where work ends and where life begins and vice versa, itself an important strategy of control by immobilizing work to &lsquo;enclosed spheres&rsquo; to make surveillance easier.<sup id="link_15"><a href="#ref_15">15</a></sup><br> The worker, objectified by capital and required only for the specific tasks assigned to them as defined by the employment contract, adhered to the strict delineation between work and play: &ldquo;When we are at work, we ought to be at work. When we are at play we ought to be at play. There is no use trying to mix the two. When the work is done, then the play can come, but not before.&rdquo;<sup id="link_16"><a href="#ref_16">16</a></sup></p>
<p><br>Deriding the stultifying nature of Taylorist scientific-management, a form of disciplinary power preceding Fordist-Bureaucracy proper, Antonio Gramsci wrote that, &ldquo;Not only does the workerthink, but the fact that he gets no immediate satisfaction from his work and realizes that they are trying to reduce him to a trained gorilla, can lead him into a train of thought that is far from conformist.&rdquo;<sup id="link_17"><a href="#ref_17">17</a></sup> Indeed, operationalist controls only worsened the anomie of workers who, aware of their own alienation and continued exploitation under such a Fordist regime, fiercely contested it in the 1930s and 1940s, but eventually accepting its instauration and giving up their claim to production in exchange for increased consumption rates and social goods.<sup id="link_18"><a href="#ref_18">18</a></sup>&nbsp; Once more, regimeadjusting class conflict ferments and thus, &ldquo;in establishing those conditions most favorable for bureaucratic control, capitalists inadvertently have also established the conditions under which demands for workplace democracy flourish...Rising dissatisfaction and alienation among workers, made exigent by their greater job security and expectation of continuing employment with one enterprise, create problems for employers, one of which is reduced productivity.&rdquo;<sup id="link_19"><a href="#ref_19">19</a></sup></p>
<p><br>Stephen Barley and Gideon Kunda point out that, &ldquo;Although rationalization may have streamlined production, it was criticized for rewarding specialization, parochialism, and calculative involvement at the expense of loyalty and commitment.&rdquo;<sup id="link_20"><a href="#ref_20">20</a></sup> They further maintain that shifts in managerial techniques &ndash;from rational to normative strategies&ndash; can be explained through a combination of cultural (or ideological) and material (or economic) analysis: the former to explain the changing discourse of managerial strategy, the latter to explain the timing in which it occurred. Importantly, this progression did not happen linearly but rather in alternating waves that &ldquo;strongly suggests that American managerial ideology has evolved within the confines of a bipolar ideational structure.&rdquo;<sup id="link_21"><a href="#ref_21">21</a></sup> A normative rhetoric was adopted that saw management not as experts, but rather as role models to disseminate workplace values and inspire a workforce. This switch from the hard rationalism of Fordist-Bureaucracy which treated the worker as a mere cog, however, was not completely replaced but rather coexisted with the normative shifts of a post-Fordist workplace where notions of communality were gradually instilled.</p>
<p><br>The broader macroeconomic shifts of the 1970s involving a series of crises and recession (triggered by the energy shocks between 1967 and 1979) provided room for an incipient neoliberal political project even though its intellectual development began much earlier with the likes of Hayek, Friedman and the Mont Pelerin society.<sup id="link_22"><a href="#ref_22">22</a></sup> Alongside the creeping &lsquo;construction of consent&rsquo; orienting a focus towards market-fundamentalism and a culture of individualism and consumption, the Global North experienced the decline of traditional industries with the rise of the services economy where &ldquo;having matured during the 1960s, many professional workers and their blue-collar contemporaries seemed less willing to accept authority or view work as a central life interest,&rdquo; which meant that &ldquo;loyalty to the firm could no longer be taken for granted, even among the professional labor force.&rdquo;<sup id="link_23"><a href="#ref_23">23</a></sup></p>
<p><br>As an art of managerialism, the post-Fordist Bureaucracy emerges as a project of building and managing organizational culture through three tenets: first, that turbulent and competitive market environments necessitates commitment from employees who make no distinction between their own wellbeing and that of the firm; second, that strong corporate cultures can be designed and manipulated; and last, that by subsequently inculcating strong value conformity and emotional commitment, financial gain is created through heightened productivity.<sup id="link_24"><a href="#ref_24">24</a></sup> The result is the creation of a totalizing institution which &ldquo;[fosters] an all-encompassing environment in which our very personhood becomes a loyal reflection of the company.&rdquo;<sup id="link_25"><a href="#ref_25">25</a></sup></p>
<p><br>For instance, in Kunda&rsquo;s ethnographic study of a high-commitment organization in the 1980s pseudonymised as &lsquo;Tech,&rsquo; a senior manager reveals the basic thrust&ndash; &ldquo;Power plays don&rsquo;t work. You can&rsquo;t make &rsquo;em do anything. They have to want to. So you have to work through the culture. The idea is to educate people without them knowing it. Have the religion and not know how they ever got it!&rdquo;&ndash; such that everything at Tech, from cutlery and crockery to team building exercises were designed to emanate its brand and values.<sup id="link_26"><a href="#ref_26">26</a></sup> Away from the pseudo-concrete grand subjects that formed the basis of imagined communities during Fordist-Bureaucracy like &lsquo;the nation,&rsquo; the era of culture management formed one around &lsquo;the corporation.&rsquo;<sup id="link_27"><a href="#ref_27">27</a></sup> More correctly, from the national corporation to the multinational one.</p>
<p><br>Against the systems-rationalism at the tail-end of Fordist-Bureaucracy, the organizational culture movement claimed to promote the autonomy of workers. Their interests, values, aims and preferences dove-tailed with that of the corporation simply because the employee supposedly had an organic affinity for it and its vision. The worker identifies with and personifies the corporation.<sup id="link_28"><a href="#ref_28">28</a></sup> Rightly suspicious, Hugh Willmott analyses the logic behind corporate culturalism through an Orwellian lens, highlighting the internal contradiction of the promise of autonomy and self-expression, but only within a prescribed value-system.<sup id="link_29"><a href="#ref_29">29</a></sup> &ldquo;The real message underlying these strong<br>cultures might read,&rdquo; Peter Fleming writes, that &ldquo;You can do what you like, just as long as you do what we tell you.&rdquo; Summarizing Willmott&rsquo;s argument, Fleming says further that, &ldquo;Corporate culturalism forcibly binds the sentimental domain of the workforce to a singular set of values in order to deepen instrumental rationality. It renders behavior more predictable, calculable, and certain from a one-dimensional economic (or instrumental) viewpoint.&rdquo;<sup id="link_30"><a href="#ref_30">30</a></sup></p>
<p>The more things changed, the more they fundamentally remained the same. Even though the ascent &nbsp;of neoliberalism rode on rhetoric about decentralization and the death of bureaucracy, Mark Fisher firmly dispels this notion in Capitalist Realism (2009):</p>
<p style="text-align: center;"><br>Initially, it might appear to be a mystery that bureaucratic measures should have<br>intensified under neoliberal governments that have presented themselves as antibureaucratic and anti-Stalinist. Yet new kinds of bureaucracy &ndash; &lsquo;aims and objectives&rsquo;, &lsquo;outcomes&rsquo;, &lsquo;mission statements&rsquo; &ndash; have proliferated, even as neoliberal rhetoric about the end of top-down, centralized control has gained pre-eminence. It might seem that bureaucracy is a kind of return of the repressed, ironically re-emerging at the heart of a system which has professed to destroy it. But the resurgence of<br>bureaucracy in neoliberalism is more than an atavism or an anomaly.<sup id="link_31"><a href="#ref_31">31</a></sup></p>
<p><br>While the old regimes have by no means disappeared, the character of control has shifted, in many ways precisely so as to conceal what hasn&rsquo;t changed, as well as what has. Facilitated by the state, neoliberalism begins with the market becoming the organizing principle of society, throwing into crisis the bedrock of institutions that once held it together&ndash; the home, the school, the factory and office&ndash; &ldquo;But everyone knows that these institutions are finished, whatever the length of their expiration periods. It&rsquo;s only a matter of administering their last rites and of keeping people employed until the installation of the new forces knocking at the door.&rdquo;<sup id="link_32"><a href="#ref_32">32</a></sup></p>
<p><a href="#link_3"><sup id="ref_3">3</sup></a> Michel Foucault, <em>Discipline and Punish: the birth of the prison&nbsp;</em>(New York: Vintage Books, 1995).</p>
<p><a href="#link_4"><sup id="ref_4">4</sup></a> Bernadette Loacker and Katharina Chudzikowski, <em>Beyond Bureaucracy, Fordism and Entrepreneurialism: On the Mutual Construction of Career Contexts and Professional Self-Identities</em> (Lisbon, Portugal: 26th Egos Colloquium, 2010), 4. Frederick Taylor&rsquo;s system of scientific management was explicitly derived from slave plantation practices, see for example R. Keith Aufhauser, &ldquo;Slavery and Scientific Management,&rdquo; The Journal of Economic History 33, no. 4 (1973): 811-824.</p>
<p><a href="#link_5"><sup id="ref_5">5</sup></a> Peter Fleming, <em>Resisting Work: The Corporatization of Life and its Discontents</em>. (Philadelphia, PA: Temple University Press, 2014), 73.</p>
<p><a href="#link_6"><sup id="ref_6">6</sup></a> Bernadette Loacker and Katharina Chudzikowski, Beyond Bureaucracy, 4.</p>
<p><a href="#link_7"><sup id="ref_7">7</sup></a> Jannis Kallinikos, &ldquo;Work, Human Agency and Organizational Forms: An Anatomy of Fragmentation,&rdquo; Organizational Studies 24, no. 4 (2003): 595-618</p>
<p><a href="#link_8"><sup id="ref_8">8</sup></a> Foucault, Discipline and Punish, 202-203. The historical context given is more is to illustrate the evolution of different methods of workplace management, not so much to pinpoint exactly when and where they were introduced. Admittedly, the timelines might not be the most precise.</p>
<p><a href="#link_9"><sup id="ref_9">9</sup></a> Fordism is used quite liberally in this essay, admittedly describing what would not have been part of Ford&rsquo;s factory set-up proper. Bernadette Loacker and Katharina&nbsp;</p>
<p><a href="#link_10"><sup id="ref_10">10</sup></a> Chudzikowski, Beyond Bureaucracy, 5.</p>
<p><a href="#link_11"><sup id="ref_11">11</sup></a> The Panopticon is described in Richard Weiskopf and Bernadette Loacker, &ldquo; &lsquo;A snake&#39;s coils are even more intricate than a mole&#39;s burrow.&rsquo; Individualisation and Subjectification in Post-disciplinary Regimes of Work. Management Revue 17, no.4 (2006), 400: &ldquo;Disciplinary power finds its ultimate realization in the Panopticon. Jeremy Bentham&rsquo;s marvelous architectural invention, which was designed as an &lsquo;inspectionhouse&rsquo; that is polyvalent in its applications and may be used &lsquo;whenever one is dealing with a multiplicity of individuals on whom a task or a particular form of behaviour must be imposed&rsquo; includes all the strategic elements of disciplinary power.&rdquo;</p>
<p><a href="#link_12"><sup id="ref_12">12</sup></a> Alan McKinlay, &ldquo;Dead Selves&rsquo;: The Birth of the Modern Career,&rdquo; Organization 9, no.4 (2002): 595&ndash;614.</p>
<p><a href="#link_13"><sup id="ref_13">13</sup></a> Max Weber, From Max Weber: Essays in Sociology (New York: Oxford University Press, 1946), 220.</p>
<p><a href="#link_14"><sup id="ref_14">14</sup></a> Erich Fromm, The Sane Society (New York: Rinehart &amp; Company Inc, 1955), 175.</p>
<p><a href="#link_15"><sup id="ref_15">15</sup></a> Zygmunt Bauman, Liquid Modernity (Cambridge: Polity Press, 2001).</p>
<p><a href="#link_16"><sup id="ref_16">16</sup></a> Huw Beynon, Working for Ford. (Harmondsworth: Penguin, 1980), 40.</p>
<p><a href="#link_17"><sup id="ref_17">17</sup></a> Antonio Gramsci, &ldquo;Taylorism and the Mechanization of the Worker,&rdquo; in Selections from the Prison Notebooks, ed. and trans. Quentin Hoare and Geoffrey Nowell Smit (London: Elecbook, 1999), 139.</p>
<p><a href="#link_18"><sup id="ref_18">18</sup></a> Michael Masuch, &ldquo;Vicious circles in organizations.&rdquo; Administrative Science Quarterly 30, (1985): 14-33; cited in Stephen R. Barley and Gideon Kunda, &ldquo;Design and Devotion: Surges of Rational and Normative Ideologies of Control in Managerial Discourse,&rdquo; Administrative Science Quarterly 37 (1992),<br>382.</p>
<p><a href="#link_19"><sup id="ref_19">19</sup></a> Richard Edwards, Contested Terrain,153-154.</p>
<p><a href="#link_20"><sup id="ref_20">20</sup></a> Stephen R. Barley and Gideon Kunda, &ldquo;Design and Devotion,&rdquo; 82.</p>
<p><a href="#link_21"><sup id="ref_21">21</sup></a> Ibid., 385.</p>
<p><a href="#link_22"><sup id="ref_22">22</sup></a> David Harvey, A Brief History of Neoliberalism (Oxford: Oxford University Press, 2005).</p>
<p><a href="#link_23"><sup id="ref_23">23</sup></a> Stephen R. Barley and Gideon Kunda, &ldquo;Design and Devotion,&rdquo; 380.</p>
<p><a href="#link_24"><sup id="ref_24">24</sup></a> Stephen R. Barley and Gideon Kunda, &ldquo;Design and Devotion,&rdquo; 382&ndash;383.</p>
<p><a href="#link_25"><sup id="ref_25">25</sup></a> Fleming, Resisting Work, 89.</p>
<p><a href="#link_26"><sup id="ref_26">26</sup></a> Gideon Kunda, Engineering Culture: Control and Commitment in a High Technology (Philadelphia, PA: Temple University Press, 1992), 5.</p>
<p><a href="#link_27"><sup id="ref_27">27</sup></a> Per Stephen R. Barley and Gideon Kunda, &ldquo;Design and Devotion,&rdquo; 383: &ldquo;To make the point, proponents employed an imagery of cults, clans, and religious conversions...Authors exhorted managers to become the &lsquo;high priests&rsquo; of their organization&#39;s values, to appoint &lsquo;mythical heroes,&rsquo; and to fabricate &lsquo;sagas.&rsquo;&rdquo; See also<br>William G. Ouchi and Raymond C. Price, &ldquo;Hierarchies, Clans and Theory Z: A New Perspective on OD,&rdquo; Organizational Dynamics 7 (1978): 24-44; Terrence E. Deal and Allan A. Kennedy, Corporate Cultures (Reading, MA: Addison-Wesley, 1982); and R.M Donnelly, &ldquo;The Interrelationship of Planning with Corporate Culture in the Creation of Shared Values,&rdquo; Managerial Planning 32 (1984): 8-12.</p>
<p><a href="#link_28"><sup id="ref_28">28</sup></a> Gideon Kunda, Engineering Culture, 11.</p>
<p><a href="#link_29"><sup id="ref_29">29</sup></a> Hugh Willmott, &ldquo;Strength Is Ignorance; Slavery Is Freedom: Managing Cultures in Modern Organizations,&rdquo; Journal of Management Studies 30, no.4 (1993): 526.</p>
<p><a href="#link_30"><sup id="ref_30">30</sup></a> Fleming, Resisting Work, 91.</p>
<p><a href="#link_31"><sup id="ref_31">31</sup></a> Mark Fisher, Capitalist Realism: Is There No Alternative? (Winchester, UK: Zero Books, 2009), 40.</p>
<p><a href="#link_32"><sup id="ref_32">32</sup></a> Gilles Deleuze, &ldquo;Postscript on the Societies of Control,&rdquo; L&rsquo;Autre journal, no. 1 (1990): 4.</p>`
//ends at 32 
let neoliberalism_text = `<p><br>In Undoing the Demos (2015), Wendy Brown gives a compelling case for why neoliberalism impoverishes the political imagination and hollows out contemporary liberal democracy, the very thing it claims to enhance. Brown understands neoliberalism as a &ldquo;normative order of reason developed over three decades into a widely and deeply disseminated governing rationality, neoliberalism transmogrifies every human domain and endeavour, along with humans themselves, according to a specific image of the economic. All conduct is economic conduct; all spheres of existence are framed and measured by economic terms and metrics.&rdquo;<sup id="link_33"><a href="#ref_33">33</a></sup></p>
<p><br>Neoliberalism, as a paradoxically anti-normative normative-ideological project is characterized by the &lsquo;economization of everything,&rsquo; extending even to quotidian activity where the distinctly human character of social relations is converted into purely economic relations. This is not literal, but &ldquo;Rather, the point is that neoliberal rationality disseminates the model of the market to all domains and activities&ndash;even where money is not an issue&ndash;and configures human beings exhaustively as market actors<sup id="link_34"><a href="#ref_34">34</a></sup> with market values are extended to all spheres of life. In dispensing with any metaphysical anthropology, neoliberalism is first and foremost anti-humanist.</p>
<p><br>Brown draws from Foucault&rsquo;s 1978-1979 Birth of Biopolitics lectures given at the College de France, wherein Foucault cast neoliberalism as a governmentality or order of reason leading to the political rationality of the state becoming economic, so as to &ldquo;regulate society by the market.&rdquo;<sup id="link_35"><a href="#ref_35">35</a></sup> Sympathetic to Foucault&rsquo;s initial analysis of its bloom, Brown captures its distinctive feature, inasmuch as its globalizing expansion is at once disunified and non-identical with itself:<sup id="link_36"><a href="#ref_36">36</a></sup></p>
<p style="text-align: center;"><br>The political rationality of the state becomes economic in a triple sense: the economy<br>is at once model, object, and project. That is, economic principles become the model<br>for state conduct, the economy becomes the primary object of state concern and<br>policy, and the marketization of domains and conduct is what the state seeks to<br>disseminate everywhere. <sup id="link_37"><a href="#ref_37">37</a></sup></p>
<p><br>Neoliberalism&rsquo;s veridiction of the &lsquo;market as truth&rsquo;, its anti-Stalinist and anti-Bureaucratic register that tries to establish itself as a project liberating the individual whilst simultaneously (and contradictorily so) indexing all of life to market values, thereby creates a totalizing reality, and what Fisher would call Capitalist Realism. Here, not only does any alternative raison de vivre seem unimaginable, but unreasonable. Neoliberalism has captured our imaginations such that we struggle to imagine a world without it, and where even our dreams are infected by it. Capitalist Realism thrives through neoliberalism, as &ldquo;an order that effectively suspends history and thereby fixes the existing state of affairs for eternity.&rdquo;<sup id="link_38"><a href="#ref_38">38</a></sup> As the emissary for capital, it is neoliberal realism that &ldquo;entails subordinating oneself to a reality that is infinitely plastic, capable of reconfiguring itself at any moment.&rdquo;<sup id="link_39"><a href="#ref_39">39</a></sup> Neoliberalism itself is a crisis, knowing not how to reproduce itself on its own terms. It is for this very reason that it relies precisely on that which it despises: that which goes beyond the reach of capital and the market.<sup id="link_40"><a href="#ref_40">40</a></sup></p>
<p><br><a href="#link_33"><sup id="ref_33">33</sup></a> Wendy Brown, Undoing the Demos: Neoliberalism&rsquo;s Stealth Revolution (Brooklyn, New York: Zone Books, 2015), 9-10. Although, Quinn Slobodian&rsquo;s recent book is a helpful corrective to the idea of neoliberalism as a vague rationality, arguing instead that it is above all an institutional doctrine. See Quinn Slobodian, Globalists: The End of Empire and the Birth of Neoliberalism (Cambridge, Massachusetts: Harvard University Press, 2018)</p>
<p><a href="#link_34"><sup id="ref_34">34</sup></a> Ibid., 31.</p>
<p><a href="#link_35"><sup id="ref_35">35</sup></a> Michel Foucault, The Birth of Biopolitics: Lectures at the Coll&egrave;ge de France, 1978&ndash;79, ed. Michel Snellart, trans. Graham Burchell (London: Palgrave, 2008), 145. There is a growing body of scholarship contextualizing Foucault&rsquo;s analysis of neoliberalism, where he viewed its anti-statist tendencies as a potential site for new subjectivities and minoritarian experiments. See Daniel Zamora and Michael C. Dehrent eds., Foucault and Neoliberalism, (Cambridge: Polity Press, 2015) and Daniel Zamora and Mitchell Dean, The Last Man Takes LSD. Foucault after 68, (Forthcoming).</p>
<p><a href="#link_36"><sup id="ref_36">36</sup></a> Brown, Undoing the Demos, 21.</p>
<p><a href="#link_37"><sup id="ref_37">37</sup></a> Ibid., 62.</p>
<p><a href="#link_38"><sup id="ref_38">38</sup></a> Michael Hardt and Antonio Negri, Empire (Cambridge, MA: Harvard University Press, 1999), xiv.</p>
<p><a href="#link_39"><sup id="ref_39">39</sup></a> Fisher, Capitalist Realism, 54.</p>
<p><a href="#link_40"><sup id="ref_40">40</sup></a> Fleming, Resisting Work, 29.</p>`

let blurred_lines_text = `<p>Dreaming about your work is one thing, but dreaming inside the logic of your work is another. . . . [I]n the kind of dream I have been having the very movement of my mind is transformed: it has become that of my job. This is unnerving.</p>
<p>&ndash;Rob Lucas</p>
<p>The global economic and social unrest beginning in the 1990s painted a picture of the corporation very different to that of the &lsquo;value holding and virtuous&rsquo; one under corporate culturalism. Not only did workers sense the falsity in the promise of autonomy within the limits of an uncompromising value structure, but a series of large scale corporate scandals, such as the oil wars, Wikileaks revelations, the growth of the anti-globalization movement and the fallouts of the 2008 global financial crisis made workers generally distrustful of corporations and their dubious doings.<sup id="link_41"><a href="#ref_41">41</a></sup> Along with the withering trust of workers, the specter of &lsquo;there is no alternative&rsquo; emboldened corporations to steadily abandon the quest for public virtue, their corruption permitted because &lsquo;it&rsquo;s just the way things are.&rsquo;</p>
<p><br>Neoliberalism, as it frequently does, encounters here a crisis of confidence around the organization of work. Neoliberalism slouches on, however, exactly because through valorizing market mechanisms it is driven by notions of flexibility and dynamism, eschewing durable frameworks such that &ldquo;business organization is increasingly seen as a never conclusive, ongoing attempt &lsquo;to form an island of superior adaptability.&rsquo; &rdquo;<sup id="link_42"><a href="#ref_42">42</a></sup> The logic of neoliberalism is to fight against the hostile world it creates. Although dynamic and expansive, this is not to say that control vanishes&ndash;instead with neoliberalism, &ldquo;capitalism is inventive and productive, and to capitalize, it progressively leaves the factory and invades, like a parasite, all spheres of life and the life-world itself. At the end, it ends up, as we shall see, producing and consuming life itself.&rdquo;<sup id="link_43"><a href="#ref_43">43</a></sup></p>
<p><br>There is a major shift wherein corporations focus less on imposing or constructing behaviours, values and knowledge, but rather try to capture or enclose on that which the individual already has; namely the ability to self-organize, socialize and to utilize one&#39;s own experience to get things done. In order to exploit that which is out of late capitalism&rsquo;s reach, new forms of control need to be devised. In order to capture limitless potential, control needs to become limitless itself. Writing of the condition of this post-disciplinary society, Zygmunt Bauman notes that, &ldquo;Whatever else the present stage in the history of modernity is, it is also, perhaps above all, post-Panoptical.&rdquo; <sup id="link_44"><a href="#ref_44">44</a></sup></p>
<p><br>Gilles Deleuze was one of the first to apprehend what the implications of a post-disciplinary world was, one suffering a &ldquo;generalized crisis in relation to all the environments of enclosure.&rdquo;<sup id="link_45"><a href="#ref_45">45</a></sup> The new social forms, in contrast to the old and with the market as cardinal principle, is that production becomes &lsquo;meta-production,&rsquo; wherein &ldquo;What [capitalism] wants to sell is services and what it wants to buy is stocks.&rdquo; The longevity of the molehill is replaced by the skin shedding serpent. What this means is that, &ldquo;the postfordistic network organization is a &lsquo;lean&rsquo; organization; management, work(ers) and capital are decentralized, hierarchies are flattened, production processes [are] increasingly immaterial, products are no longer standardized but flexible, mobile, heterogeneous, differentiated, &lsquo;knowledge-intensive&rsquo; and orientated on &lsquo;niche-markets.&rsquo; &rdquo;<sup id="link_46"><a href="#ref_46">46</a></sup></p>
<p><br>In this &lsquo;network society&rsquo; modeled in the image of developing information technologies where power is dispersed to multiple nodes, one of the first casualties are boundaries.<sup id="link_47"><a href="#ref_47">47</a></sup> The networked node nature of control makes it mobile. If &ldquo;exploitation is considered a practice of spatial and temporal confinement since control is the central motif of exploitation,&rdquo; then in societies of control where spatial confinements are increasingly blurred, exploitation and control become all pervasive.<sup id="link_48"><a href="#ref_48">48</a></sup></p>
<p><br>In 2004, Peter Fleming and Andre Spicer conducted a field study of a large call center<br>pseudonymised as &lsquo;Iocus,&rsquo; where social geography was reconfigured, and the line separating work from non-work was blurred. At Iocus, &ldquo;training workshops and everyday cultural messages constantly stress that all of those experiences employees wait until after work to have such as fun, partying, joy, fulfilment, exhilaration, friendship and even sexuality are appropriate to evoke in the workspace.&rdquo;<sup id="link_49"><a href="#ref_49">49</a></sup> They observed the work and non-work boundary dissolving first, by the transfer of the outside to the inside: non-work rituals such as consumption, leisure and spiritual development were encouraged on the site of production. Secondly, by the export of the inside to the outside, with internal corporate cultures exported to life beyond work, an example being the frequenting of a pub on Fridays which although independent, eventually came to be governed by the firm&rsquo;s sexual harassment policy.</p>
<p><br>Drawing from Gaston Bachelard, Fleming and Spicer contend that our sense of space is as much a feature of social imagination as it is the physical dimensions of the built environment.<sup id="link_50"><a href="#ref_50">50</a></sup> At Iocus therefore, it is the case that &ldquo;Although there was little difference between the built environment and what we would typically find in &lsquo;industrial&rsquo; factories and office spaces, we observed a palpable difference in how workers experienced these spatial boundaries&hellip;the boundaries between work and non-work were blurred with little change to the built environment.&rdquo; <sup id="link_51"><a href="#ref_51">51</a></sup> What Fleming and Spicer astutely point out is that transversing physical boundaries (between work and non-work) is instrumental in the often talked about psychological entanglement between life and work, wherein the two come to mean the same thing. Now, workers are asked to poetically endow or customize the workplace, to make it feel user designed and personal, in the hopes of invoking joy etc., unlike corporate culturalism which asked workers to find solidarity with the corporation&rsquo;s values.</p>
<p><br>To be sure, the older methods of management do not completely disappear but rather<br>contemporaneously exist with the new in a combination that is erratic and schizophrenic&ndash;itself an essential characteristic of the new. What has begun to predominate though, is the transformation of the built environment to complement and augment what has already settled in.&nbsp;</p>
<p>Through physical movement around the often open-planned and &lsquo;station based&rsquo; workplace, Activity Based Workplaces (ABWs) hope to increase physical, mental and social health which in turn creates organizational health, heightened productivity and cost-minimization.<sup id="link_52"><a href="#ref_52">52</a></sup> Expressed by the American office furniture brand Herman Miller in their &lsquo;Living Office&rsquo; product line: &ldquo;People are the most critical asset to every organization. So why aren&rsquo;t more offices designed to support their needs and activities?&rdquo;&nbsp;</p>
<p><br>More than simply being open-planned; comfortable and supposedly free-flowing &lsquo;organic&rsquo; movement is prioritized, with a range of facilities dedicated to specific activities as opposed to performing all tasks from the desk, all day. What&#39;s emphasized is that you deliver results, which allows one to work however and wherever they want&ndash; these workspaces provide a variety of settings, and the workday is sliced into different types of activities such as meetings, private concentration and collaborative ideation. For an illustration, one might have a meeting in a cafe-like commons for collaborative work, and then move to a sound-proofed pod for concentrated individual work, and then move again to informally sharing knowledge in a social kitchen. While the work itself might be continuous, this new spatio-temporal dimension punctuates the flow of productivity. Work feels less like a closed, uninterrupted period where it is performed, but a series of fragmented tasks completed in a given environment and celebrated as a minor victory before moving to the next; a series of finishing something without work ever ending.</p>
<p><br>What does &ldquo;socially necessary labour time&rdquo; mean if the worker spends endless hours perfecting their own personal product?&nbsp;</p>
<p>In Johannesburg, WeWork opened its doors for the first time in 2019&ndash; one in Rosebank, and another in Sandton. A tour of WeWork is enough to give a sense of its essential features (visited only a week after its official opening, it nevertheless bustled with life), although admittedly a more comprehensive empirical study is probably useful. WeWork in Rosebank occupies six floors of the Link, a stunning newly erected building housing offices at the doorstep of the Rosebank shopping complex, plus the Gautrain station (Africa&rsquo;s first high-speed underground rail transport). Upon entering the ground floor consisting of black tiles, lighting and a water feature, the atmosphere is dark, cool and tranquil. Instructed to take an elevator to the sixth floor, the doors open to the WeWork reception and light powerfully floods in&ndash; a bit disorienting. The core of the building is hollowed out for the waiting area, the WeWork offices inhabiting the building&rsquo;s periphery behind transparent glass, all life within exposed. This liminal space flips the old Panopticon model. No longer a space associated with the fear of inspection by the big Other, it is instead injected with the warmth of welcoming and receiving a potential &lsquo;community member&rsquo;. If the old Panopticon is a hellish prison-like fortress where you would hate to be behind the bars, WeWork at The Link is more like an ethereal heaven, where one longs for the other side, to be behind the glass &ndash; its seductive architecture and design deliberate.</p>
<p><br>Once inside&ndash;by no means an easy process, security is tight and access around the building is regulated by a passport-like access card&ndash; you basically walk straight into a coffee bar, which doubles as a (another) reception desk. While awaiting the tour guide, complimentary coffee is served (on this day by a deaf barista, an immediate grandstand to inclusivity and diversity of course, what Nancy Fraser calls &lsquo;progressive neoliberalism&rsquo;). The space is pimped out with fruit water dispensers, beer taps (for the time being serving ginger beer until an alcohol license is obtained), table tennis, foosball&hellip; the works at WeWork! Indeed, the place is &ldquo;all about the vibe.&rdquo; The membership tiers at different prices range from private offices, hot desks, dedicated desks and lab desks each giving different benefits and utilities, all with access to common shared spaces such as sound-proof pods, communal areas and the programmes and activations.</p>
<p><br>The day of this tour was a &ldquo;Wellness Wednesday,&rdquo; where WeWorkers are treated to a complimentary healthy breakfast, a salad bar throughout the day, a stretching and mindfulness session in the morning and a yoga workshop in the evening. Tenants are offered discounted rates to the nearby gym, and for convenience sake, there are showers downstairs. The Thursday after would have been a day experimenting with world cuisine (that week, Mexican Thursday) with a happy hour between four and five p.m. Following the weekend, members return to work, or given the 24/7 access, perhaps even staying at work until TGIM, &ldquo;Thank God It&rsquo;s Monday,&rdquo; WeWork&rsquo;s signature effort to kickstart the weekly rat-race with energy and enthusiasm by hosting motivational talks or treating members to a cultural performance (recently, acclaimed South African rapper Khuli Chana gave a silent concert, the audience tuned in via headphones).</p>
<p><br>At WeWork, &ldquo;everything is taken care of, all you do is focus on your work.&rdquo; Members can even make WeWork their personal postal address and have parcels, bills and other goods delivered straight to them. The WeWork community team focuses on creating &ldquo;the experience that you want&rdquo; through community, space and service. One of their &ldquo;social strategies to bring people together&rdquo; include their own social network with an internal currency system used for pre-booking &ldquo;brainstorm rooms,&rdquo; as well as to connect with the WeWork community locally and globally, seeing details about other members&rsquo; business, projects and ambitions. And to create a uniquely African version of the WeWork experience, &lsquo;African-styled&rsquo; artworks and design are dotted around the workplace. &ldquo;You feel at home in being at work,&rdquo; the tour guide casually remarks. WeWork is about &ldquo;finding balance within the space.&rdquo;</p>
<p><br>Amidst the crisis of neoliberalism and the accompanying disillusionment with work, leading many to view it simply as a means to a paycheck, WeWork provides an answer: to &ldquo;make a life, not just a living.&rdquo;</p>
<p><br><a href="#link_41"><sup id="ref_41">41</sup></a> Fleming, Resisting Work, 102.</p>
<p><a href="#link_42"><sup id="ref_42">42</sup></a> Bauman, Liquid Modernity, 117.</p>
<p><a href="#link_43"><sup id="ref_43">43</sup></a> Fr&eacute;d&eacute;ric Vandenberghe, &ldquo;Deleuzian capitalism,&rdquo; Philosophy &amp; Social Criticism 34, no.8 (2008): 878.&nbsp;</p>
<p><a href="#link_44"><sup id="ref_44">44</sup></a> Bauman, Liquid Modernity, 11. Bauman does not think that surveillance disappears because of this, but rather is expanded through its very diffusion.</p>
<p><a href="#link_45"><sup id="ref_45">45</sup></a> Deleuze, &ldquo;Postscript on the Societies of Control,&rdquo; 3.</p>
<p><a href="#link_46"><sup id="ref_46">46</sup></a> Loacker and Chudzikowski, Beyond Bureaucracy, Fordism and Entrepreneurialism, 8.</p>
<p><a href="#link_47"><sup id="ref_47">47</sup></a> See Weiskopf and Loacker, &ldquo; Individualisation and Subjectification in Post-disciplinary Regimes of Work,&rdquo; 404: &ldquo;A network consists of a number of interconnected nodes. In contrast to the positions in the Panopticon (confined cells), the nodes of the network are open and changeable. The Panopticon worked by cutting off communication between different points. In this way, it made sure that the central point had complete mastery of information&hellip;In the network there is no single centre of power; rather, power is distributed to multiple nodes, in which information, resources, etc. come together or are connected&hellip;Those in the network are not subjected to hierarchical visibility in the same way as inmates of the Panopticon. In<br>the network the control of flows (e.g of information, resources, money) and the establishing of rules and<br>access are important.&rdquo;</p>
<p><a href="#link_48"><sup id="ref_48">48</sup></a> Fleming, Resisting Work, 106.</p>
<p><a href="#link_49"><sup id="ref_49">49</sup></a> Peter Fleming and Andre Spicer, &ldquo; &lsquo;You can check out anytime, but you can never leave&rsquo;: Spatial<br>boundaries in a high commitment organization,&rdquo; Human Relations 57 (2004): 83.</p>
<p><a href="#link_50"><sup id="ref_50">50</sup></a> See Gaston Bachelard, The poetics of space, trans. Maria Jolas (Boston, MA: Beacon Press, 1958), 56; quoted in Fleming and Spicer, &ldquo;Spatial boundaries in a high commitment organization,&rdquo; 88-89. Lived space becomes a &lsquo;concrete abstraction&rsquo;: &ldquo;The objective space of a house &ndash; its corners, corridors, cellars, rooms &ndash; is far less important than what it is poetically endowed with, which is usually a quality with an imaginative or figurative value we can name and feel: thus a house may be haunted or homelike, or prison-like or magical.&rdquo;</p>
<p><a href="#link_51"><sup id="ref_51">51</sup></a> Fleming and Spicer, &ldquo;Spatial boundaries in a high commitment organization,&rdquo; 88.</p>
<p><a href="#link_52"><sup id="ref_52">52</sup></a> The earliest conceptions of office space through activity settings comes from American architects Phillip J. Stone and Robert Luchetti, &ldquo;Your office is where you are,&rdquo; Harvard Business Review 63, no. 2 (1985):<br>102-117.</p>`

let working_text = `<p>We should understand WeWork as emblematizing the burgeoning Activity Based Workplace model, not as being the definitive example of this phenomenon, nor as an indication that older managerial regimes have faded. As pointed out earlier, what is happening now is more of the physical concretization (in the built environment) of a process whose material and ideological underpinnings have already taken hold. These new developments in the architecture and interior design of the workplace, if anything, are spurred on by technological advances&ndash; not driven by them, but made easier through them, such that the increasingly portable nature of technological devices and the &lsquo;appification&rsquo; of the workplace allows one to be mobile whilst tethered to work, smoothing the dissolution of boundaries.</p>
<p>Fleming adapts the Foucauldian concept of biopower to explain the corporate colonization of life by work, identifying it as another form of capitalist domination and exploitation. Biopower, per Fleming, exploits the human capacity to be socially, emotionally and cognitively intelligent, innovative and resilient. These qualities are developed outside of the workplace, and are immeasurable by the formal dictates of economic rationality&ndash; in fact, they are antithetical to the anti-social precepts of neoliberal rationality which casts human beings as unimpeachably rational and self-maximizing agents, homo oeconomicus. Fleming writes that, &ldquo;A good deal of recent management thinking has concluded that it is very difficult to force workers to yield their goodwill and non-commercialized knowhow within a formal setting...Thus emerges a new and distinct method for exploiting living labor. These processes seek to access the independent competencies of employees through moments of capture rather than composition.&rdquo;</p>
<p><br>The truth is, key elements of biopower aren&rsquo;t all that new. Marxist Feminists, for example, have for years described how social and reproductive labour performed by women, involving child-rearing, domestic work and social provisioning are extra-work efforts in service to capitalism and its viability, but ignored and uncompensated for. Similarly, Marxist Feminists have described the affective labour involving human contact and demanding social affability which is required in the care industries (such as nursing) that are dominated by women. Neoliberalism<sup id="link_53"><a href="#ref_53">53</a></sup> sustains a conception of the family that stabilizes these roles by naturalizing women as caring, generous and compassionate &ndash; traits to be acted out both inside the home and family, and throughout the various jobs they occupy outside of it.<sup id="link_54"><a href="#ref_54">54</a></sup></p>
<p><br>South Africa and other developing or post-colonial nations have unique and complex histories where the transformation of the work order happens variably, particularly given the already attendant precarity and casualization of the majority of the workforce prior to and with neoliberalism (formalisation was never capital&rsquo;s preferred mode of employment). As Karl von Holdt and Edward Webster point out, South Africa &ldquo;never experienced the successful construction of a welfare state through the counter-movement of society in response to the market forces of the [settler-colonial/apartheid state] transformation.&rdquo; While <sup id="link_55"><a href="#ref_55">55</a></sup> formal racial integration into the workforce exists, persisting alongside this are the old lines of exclusion and inclusion bifurcated into core and non-core zones of formal sector employment, as well as peripheral work that is not about &ldquo;earning a living&rdquo; through regular pay, but &ldquo;making a living&rdquo; by creating one&rsquo;s own income or through subsistence activities.<sup id="link_56"><a href="#ref_56">56</a></sup></p>
<p><br>According to Franco Barchiesi, the South African crisis of structural underemployment then, requires for many, &ldquo;Strategies of self-employment [requiring] the activation of social networks, life experiences and cognitive abilities that are mostly invisible and marginalized in the factory routine.&rdquo;<sup id="link_57"><a href="#ref_57">57</a></sup> In the present age, &ldquo;African post-Fordism is more about &lsquo;out of luck&rsquo; than &lsquo;just-in-time&rsquo; as the future uncertainties of informal entrepreneurship are grounded in present assets that depend on social networks, chiefly the family, undermined by the same global dynamics that make waged work redundant in the first place.&rdquo;<sup id="link_58"><a href="#ref_58">58</a></sup> South Africa&rsquo;s history of rapid accumulation premised on the suppression and exclusion of its black population meant that the self-sustenance of the underclasses demanded putting life to work. In post-Apartheid South Africa, neoliberalism means life is put to work for the reproduction of the whole society, extending an ever-existing precarity for black South Africa.</p>
<p><br>What is new about these contemporary instantiations of biopower, is it is no longer relegated to the shadows where its force is unseen, but instead enlisted explicitly in all forms of work even in the formal sector, and used to reproduce neoliberal society at large. Before, biopower was part of a societal underbelly, life to be occasionally recruited, but life before or beyond work. Now, the exercise of biopower has become fundamental to managerial strategy.</p>
<p><br>Biopower lives in Activity Based Workplaces rent free, and is extended outside of them as well. Liberated from spatio-temporal confinement, Melissa Gregg describes how work becomes an omnipotent reality through &ldquo;presence bleed&rdquo;, where workers are always mentally on the job; as well as &ldquo;functional creep&rdquo;, the widening array of work that depends on workers informal knowhow and self-organizing abilities. Penetrating through spatio-temporal <sup id="link_59"><a href="#ref_59">59</a></sup> confinement, &ldquo;firm boundaries between personal and professional identities no longer apply. Presence bleed explains the familiar experience whereby location and time of work become secondary considerations faced with the &lsquo;to<br>do list&rsquo; that seems forever out of control.&rdquo;<sup id="link_60"><a href="#ref_60">60</a></sup></p>
<p><br>How do ABWs intensify this? The internal arrangement of ABWs are intended to be a simulacrum of real life, breaking work-time into splintered activities across different settings and environments. The very movement of life operates by the pursuit of settings to conduct an activity&ndash; a park for recreation, a supermarket for groceries, a clinic for treatment etc. Since no person views their life as something with end, in mimicking the constant passage of life, work colonizes time without end:</p>
<p style="text-align: center;"><br>This phantasmagoria of permanence or endlessness is one of neoliberalism&rsquo;s<br>crowning achievements. Indeed, we have known for a while that capitalism<br>exploits us primarily through time: time at work, time thinking about work, time<br>prepping for work. What makes neoliberalism so much more radical than earlier<br>modes of capitalist control lies in the way it infinitizes the otherwise finite register<br>of work, erasing any sense of end or beginning. After that, there is no alternative<br>to working life.<sup id="link_61"><a href="#ref_61">61</a></sup></p>
<p><br>Beyond this movement dimension, activities and amenities that signal &lsquo;life beyond work&rsquo; are now part of &lsquo;life within work.&rsquo; Leisurely and recreational rituals, such as drinking and spiritual development are enacted within the workplace itself under the guise of creating a work-life balance.<sup id="link_62"><a href="#ref_62">62</a></sup> Coinciding with the neoliberal assault on public goods, increasing privatization, and the triumph of a society of consumers, the worker now feels as if they have to be at work in order to be &lsquo;balanced&rsquo;&ndash; the park, the public gym, the post office no longer belong to the public domain. Leisure itself only moved into the realm of necessity because work was so insufferable, and because work was so insufferable, it recuperated leisure as its savior. Escape from work is now in work.</p>
<p><br>Another corporation opening new offices was Discovery, a popular company specializing in medical aid, life and car insurance, as well as banking. Their plush new headquarters in Sandton, curiously aren&rsquo;t owned by them, instead they pay about $1.5 million to rent it each month. On top of incorporating agile working environments, the building contains an impressive collection of utilities: a mechanic, a carwash, a tailor, a medical centre, a gym, a rooftop basketball court, a rooftop running track, a home affairs, a collection of restaurants and coffee shops, salons and hairdressers, and a creche one kilometer down the road. Inside, ninety-two indigenous trees were planted, earning Discovery a five star rating from the Green Building Council&ndash; &ldquo;The air inside this building is better than the air outside,&rdquo; boasts the tour guide, and workers are to plant a tree if they consume bottled water in the building. Employees are encouraged to keep fit, and are not allowed to take the elevator a level up or down. Community is encouraged through shared spaces, and the elevators compel employees to move through the general concourse area in order to enter or leave the building.</p>
<p><br>Beyond work, an offering available to Discovery customers as well as their workers, are their numerous reward programmes, which include discounts on movie tickets, air tickets, gym memberships, supermarkets and retailers as well as transport like Uber. Discovery takes on the role of life giver, an almost benevolent God of capitalism, their clientele and employees remade as their citizens. While Foucault originally associated biopower with the disciplinary welfare state, in the neoliberal society of control, life is administered by the corporation.</p>
<p><br>Biopower is capitalism&rsquo;s response to its own, innate crisis tendencies, its inability to reproduce itself on its own accord, so it capitalizes and exploits that which lies beyond the clutches of the corporation. However, this was not enough to placate an already skeptical workforce who, firstly, were already disillusioned with work, and secondly could notice its colonizing effects making things worse. As work-related anxiety, burnout, purposeless and meaninglessness rose, this contributed to what Paolo Virno called a lasting sense of &ldquo;not feeling at home.&rdquo;<sup id="link_63"><a href="#ref_63">63</a></sup> ABWs provide the solution: to transform how you work&ndash; not why or what it is, but instead rendering it as something that can be fun when performed, and that offers us a balanced life with the prospects of self-betterment. ABWs bring life to work, and therefore make work a home.</p>
<p><br>In spite of the totalitarian expansion of work into life and life into work, the worker is told that they possess unprecedented levels of autonomy and freedom in the workplace, exactly for the reason that the worker is asked to cheerfully bring their subjective experience to work. This mythology is constructed by the &ldquo;integration of ever more aspects of social personality into the production process, [which] dismantles the usefulness of the boundary between work and life.&rdquo;<sup id="link_64"><a href="#ref_64">64</a></sup> ABWs are built having in mind what Jody Thompson and Cali Ressler call a &ldquo;Results Only Work Environment&rdquo;, where work is organized primarily around output (as opposed to hours worked).<sup id="link_65"><a href="#ref_65">65</a></sup> This lends itself completely to the self-organization and free movement of the worker&ndash; &ldquo;The message now is &lsquo;Be yourself, say what you like, but submit to the demands of economic necessity.&rsquo; &rdquo;<sup id="link_66"><a href="#ref_66">66</a></sup></p>
<p><br>The difficulty with immaterial labour which is communicative, affective, creative, symbolic or emotional, is that it is difficult to measure in economic terms&ndash;&ldquo;When the inexhaustible facets of living labor come to the fore in the production matrix, it also inspires an almost limitless multiplication of surveillance and standardization.&rdquo;<sup id="link_67"><a href="#ref_67">67</a></sup> The nature of work today involving highly subjective elements and processes makes managerial supervision according to objective dictates obsolete. Still, the class antagonism remains, and the presence of self-managing teams and the like go against management&rsquo;s instincts to supervise, command and control. Therefore, &ldquo;From capital&rsquo;s perspective, the predicament of immeasurability is met by activating time-tested forms of domination: not less but an overabundance of regulation&mdash;just to make sure. Indeed, it is not a coincidence that at the very moment that &ldquo;trust,&rdquo; &ldquo;empowerment,&rdquo; and &ldquo;just be yourself&rdquo; enter the lexicon of neo-corporatism, we also see a tremendous rise in management distrust.&rdquo;<sup id="link_68"><a href="#ref_68">68</a></sup></p>
<p><br>Recall Fisher&rsquo;s comments on the proliferation of &lsquo;aims and objectives&rsquo;, &lsquo;mission statements&rsquo; and &lsquo;outcomes.&rsquo; Although top-down control has flattened, regulation nevertheless continues, however dressed in nebulous language that obfuscates their coercive intention. Brown describes neoliberal regulation as, &ldquo;[replacing] orders with orchestration, enforcement with benchmarks and inspection, mandate with mobilization and activation&hellip; Together, these replacements also vanquish a vocabulary of power, and hence power&rsquo;s visibility, from the lives and venues that governance<br>organizes and directs.&rdquo;<sup id="link_69"><a href="#ref_69">69</a></sup></p>
<p><br>Even so, without the surplus regulation implemented by management, the discourse of<br>empowerment is a sleight manifestation of the technologies of responsibilization&ndash;<br>&ldquo;Responsibilization brings individuals closer to the various clients (or customers) and makes their demands immediately their own personal concern.&rdquo;<sup id="link_70"><a href="#ref_70">70</a></sup> Individuals undertake the aims and functions of management, becoming self-disciplining and self-regulating subjects. In self-managing teams for example, the pressure to produce is horizontalised, &ldquo;resulting in employees feeling inexplicably guilty or disloyal if they failed to meet a deadline.&rdquo;<sup id="link_71"><a href="#ref_71">71</a></sup> Peer-to-peer surveillance does not only operate in teams, or even amongst colleagues in the same firm. At WeWork, for example, one is not productive because of the threat of a boss or colleague checking up on you, but rather through the unabating productive energies of those who surround you that would ostracise you if you were not productive too. In this case, by simply sharing the same space, one is surveilled even by those who are not directly working or affiliated with you.</p>
<p><br>This networked surveillance is aided by the ideology of work itself, given new articulation in the form of &ldquo;hustle culture.&rdquo; What this means is that as much as the contemporary workplace supposedly facilitates the freedom of the individual, if the individual decided not to work, not only would the individual be cast as irresponsible, but as a failed enterprise. Networked surveillance is, &ldquo;increasingly limitless, dynamic, free-floating and &lsquo;creative&rsquo;: the market operates &lsquo;like a telescope&rsquo;, an &lsquo;information machine&rsquo;, a &lsquo;machine of seeing&rsquo; &ndash; a &lsquo;panspectron&rsquo; ; it continuously assesses and evaluates individuals, their information flows (instead of their bodies) and their performances. Within post-Fordism the disciplinary technique of &lsquo;examination&rsquo; is substituted [for] the technique of &lsquo;permanent assessment&rsquo; .&rdquo;<sup id="link_72"><a href="#ref_72">72</a></sup></p>
<p><br>An important thing is revealed in the new era of work: the transformation of worker&rsquo;s subjectivity. As all social areas simultaneously become sites of work, production and reproduction, the worker becomes an &ldquo;entrepreneur of the self,&rdquo; transformed from their status as a waged-laborer into human capital. This reimagines the worker as both an enterprise and an employee, a so-called &ldquo;entreployee.&rdquo;<sup id="link_73"><a href="#ref_73">73</a></sup> The worker becomes a capitalized asset of embodied skills, attributes and competencies which must be adaptable but steady, co-operative but independent, reliable but disposable.<sup id="link_74"><a href="#ref_74">74</a></sup> More important than having a firm set of specific skills, individuals are obliged to &lsquo;reskill&rsquo; in preparation for potential prospective jobs (another instance of responsibilization), what Ilana Gershon would call &ldquo;The Quitting Economy&rdquo;, wherein &ldquo;employees are treated as short-term assets [that] reinvent themselves as marketable goods, always ready to quit.&rdquo;<sup id="link_75"><a href="#ref_75">75</a></sup></p>
<p><br>&ldquo;If your goal is to get a job somewhere else, not all work projects are equally valuable. Workers must jockey for the tasks and projects that might lead to a job elsewhere. They must try to avoid tasks that, either due to intellectual property issues or for other reasons, are too companyspecific.&rdquo; <sup id="link_76"><a href="#ref_76">76</a></sup> Any free time is dedicated to looking for other, better jobs, re-skilling, or boasting about your love for work, and marketing yourself as a desirable, employable commodity over social media, from Twitter and Instagram, to LinkedIn and Academia.edu. This exemplifies how we &lsquo;work to get work.&rsquo; The entreployee, made into capital and recast as an enterprising subject must always<br>and everywhere stay on brand.</p>
<p><br>Herein lies a fundamental contradiction about the new world of work. While the Activity Based Workplace seeks to create a social environment that gives and traps life, neoliberal reason that conceives of individuals as the anti-social homo oeconomicus perseveres. A supposedly lifeaffirming workplace culture, is belied by the life-denying reality of neoliberal realism. Beneath the appearance of community and freedom, workers are submitted to the logic of competition and individualism, further atomized, further alienated. Not only does this eliminate conditions for workplace solidarity, but it obscures the class antagonism between workers and capital that forms<br>the basis of building any resistance.</p>
<p style="text-align: center;"><br>The transformation of work to an ever-present, all-encompassing pathology cuts through class, although distributing its material and psychosocial burdens unevenly. Writing of contemporary capitalist social relations, Fleming highlights that the problem is &ldquo;not about having too little time away from our jobs. Contemporary cognitive capitalism requires that we have plenty of that. Some take holidays (if they are lucky), weekends, and so forth. Neoliberalism does not function by totally colonizing these non- work spaces. It wouldn&rsquo;t survive if it did. All it needs to do is index them to the ideology of work.&rdquo;<sup id="link_77"><a href="#ref_77">77</a></sup> The condition of our working lives and living work afflicts all&ndash; those employed, those precariously or underemployed, and even those unemployed. Indeed:</p>
<p style="text-align: center;"><br>This is more than just fear of possible unemployment or precarity. For that is an<br>objectively rational response to the present situation. The widespread anxiety and<br>hopelessness I am referring to is mostly needless, a political invention built into the<br>very logic of work today. This makes its universalization seem inevitable and<br>inescapable. In other words, when our jobs become the index for living as such, our<br>fear becomes existential and seemingly without object. And the problem with fear is<br>that it tends to individualize its victims, and we find it difficult to resist without<br>turning on ourselves; it activates and promulgates the very power effects that we now<br>need to refuse within the current biopolitical situation. <sup id="link_78"><a href="#ref_78">78</a></sup></p>
<p><br>The global, political, ecological and social breakdown that defines neoliberalism has led many to lose confidence in its ability to deliver a just and fair society, equitable for the majority. Despite this bumbling disaffection, it seems nevertheless to march on&ndash; here Gramsci is evergreen: &ldquo;The crisis consists precisely in the fact that the old is dying but the new cannot be born; in this interregnum a great variety of morbid symptoms appear.&rdquo;<sup id="link_79"><a href="#ref_79">79</a></sup> Deleuze, however, warns that, &ldquo;There is no need to fear or hope, but only to look for new weapons,&rdquo; and Fisher gives us reason for the will to persevere: &ldquo;From a situation in which nothing can happen, suddenly anything is possible again.&rdquo;<sup id="link_80"><a href="#ref_80">80</a></sup> We should grasp at neoliberalism&rsquo;s own unraveling, and if it seeks to conquer and colonize life itself, then our path is clear, and so is our task: to remake life and work anew.</p>
<p><br><a href="#link_53"><sup id="ref_53">53</sup></a> For a contemporary discussion of these concepts and women&rsquo;s oppression amid a neoliberal assault on public services and communities, see Tithi Battacharya, ed., Remapping Class, Recentering Oppression (London: Pluto Press, 2017).</p>
<p><a href="#link_54"><sup id="ref_54">54</sup></a> Brown, Undoing the Demos, 99-107.</p>
<p><a href="#link_55"><sup id="ref_55">55</sup></a> Karl von Holdt and Edward Webster, &ldquo;Work Restructuring and the Crisis of Social Reproduction: A Southern Perspective,&rdquo; in Beyond the Apartheid Workplace: Studies in Transition, ed. Edward Webster and Karl von Holdt (Scottsville: University of KwaZulu-Natal Press, 2005): 34.</p>
<p><a href="#link_56"><sup id="ref_56">56</sup></a> Ibid., 4.</p>
<p><a href="#link_57"><sup id="ref_57">57</sup></a> Franco Barchiesi, Precarious Liberation: Workers, the State, and Contested Social Citizenship in Postapartheid South Africa (Albany: State University of New York Press, 2011): 202.</p>
<p><a href="#link_58"><sup id="ref_58">58</sup></a> Ibid., 204.</p>
<p><a href="#link_59"><sup id="ref_59">59</sup></a> Melissa Gregg, Work&rsquo;s Intimacy (Cambridge, UK: Polity, 2011).</p>
<p><a href="#link_60"><sup id="ref_60">60</sup></a> Ibid., 2.</p>
<p><a href="#link_61"><sup id="ref_61">61</sup></a> Fleming, Resisting Work, 41.</p>
<p><a href="#link_62"><sup id="ref_62">62</sup></a> In a fascinating new book, Ron Purser examines how the corporate mindfulness movement and language of &lsquo;self-care&rsquo; becomes a tool of compliance: Ronald Purser, McMindfulness: How Mindfulness Became the New Capitalist Spirituality (London, UK: Repeater Books, 2019).</p>
<p><a href="#link_63"><sup id="ref_63">63</sup></a> Paolo Virno, A Grammar of the Multitude: For an Analysis of Contemporary Forms of Life (Los Angeles: Semiotext(e), 2004): 34.</p>
<p><a href="#link_64"><sup id="ref_64">64</sup></a> Fleming, Resisting Work, 108.</p>
<p><a href="#link_65"><sup id="ref_65">65</sup></a> Carli Ressler and Jody Thompson, Why Work Sucks and How to Fix It: The Results Only Revolution (New York: Portfolio).</p>
<p><a href="#link_66"><sup id="ref_66">66</sup></a> Fleming, Resisting Work, 96.</p>
<p><a href="#link_67"><sup id="ref_67">67</sup></a> Ibid., 37.</p>
<p><a href="#link_68"><sup id="ref_68">68</sup></a> Ibid., 38.</p>
<p><a href="#link_69"><sup id="ref_69">69</sup></a> Brown, Undoing the Demos, 127, 129.</p>
<p><a href="#link_70"><sup id="ref_70">70</sup></a> Weiskopf and Loacker, &ldquo; Individualisation and Subjectification in Post-disciplinary Regimes of Work,&rdquo; 409.</p>
<p><a href="#link_71"><sup id="ref_71">71</sup></a> Fleming, Resisting Work, 36.</p>
<p><a href="#link_72"><sup id="ref_72">72</sup></a> Loacker and Chudzikowski, Beyond Bureaucracy, Fordism and Entrepreneurialism, 11.</p>
<p><a href="#link_73"><sup id="ref_73">73</sup></a> Ibid., 9.</p>
<p><a href="#link_74"><sup id="ref_74">74</sup></a> John Storey, Graeme Salaman and Kerry Platman, &ldquo;Living with Enterprise in an Enterprise Economy: Freelance and Contract Workers in the Media,&rdquo; Human Relations 58, no.8 (2005): 104.</p>
<p><a href="#link_75"><sup id="ref_75">75</sup></a> Ilana Gershon, &ldquo;The Quitting Economy.,&rdquo; Aeon, July 26, 2017, <a href="https://aeon.co/essays/how-work-changed-to-make-us-all-passionate-quitters" target="_blank">https://aeon.co/essays/how-work-changedto-make-us-all-passionate-quitters</a>.</p>
<p><a href="#link_76"><sup id="ref_76">76</sup></a> Ibid.</p>
<p><a href="#link_77"><sup id="ref_77">77</sup></a> Fleming, Resisting Work, 130.</p>
<p><a href="#link_78"><sup id="ref_78">78</sup></a> Ibid.,126.</p>
<p><a href="#link_79"><sup id="ref_79">79</sup></a> Antonio Gramsci, Quaderni del Carcere, vol. 1, Quaderni 1&ndash;5 (Turin: Giulio Einaudi editore, 1977), 311. English translation quoted from Selections from the Prison Notebooks of Antonio Gramsci, ed. and trans. Quintin Hoare and Geoffrey Nowell-Smith (London: Lawrence &amp; Wishart, 1971), 276.</p>
<p><br><a href="#link_80"><sup id="ref_80">80</sup></a> Deleuze, &ldquo;Postscript on the Societies of Control,&rdquo; 4; Fisher, Capitalist Realism, 81.</p>`

let children_text = `<p>The fact that labor is external to the worker &ndash; i.e., does not belong to his essential being; that he, therefore, does not confirm himself in his work, but denies himself, feels miserable and not happy, does not develop free mental and physical energy, but mortifies his flesh and ruins his mind. Hence, the worker feels himself only when he is not working; when he is working, he does not feel himself. He is at home when he is not working, and not at home when he is working</p>
<p><br>&ndash;Karl Marx</p>
<p>In a COVID world, the worker is at home when she is working and not working when she is at home. Work has now migrated to the sanctuary of life &ndash; the home.&nbsp;</p>
<p>Zoom and other video conferencing/work enabling apps have turned into invasive microscopes for previously private parts of our lives, and telescopes into the lives of others, creating the illusion of connectedness,and obscuring hierarchy now that we can all see each other in that depoliticised environment of the home. There are no divides, are all Zoomers now. The &lsquo;appification&rsquo; of the workplace, already present in a pre-COVID-19 world, is further amplified in this moment of pandemic as we upload our lives online to ironically avoid virus contagion.&nbsp;</p>
<p><br>Zoom and MS Teams as platforms could be seen as managerial techniques that instrumentalize the language and visuality of teamwork and &lsquo;togetherness&rsquo;, exploiting and capitalising on our collective sense of isolation and loneliness in a time in which we desire a sense of collectivity and connectivity the most. Not only has work migrated to the sanctuary of life &ndash; the home &ndash; which has been sucked of its joy, and in which we now feel depressed and isolated &ndash; but it also falsely comes to represent an opportunity for connectivity and collectivity again.<sup id="link_81"><a href="#ref_81">81</a></sup></p>
<p><br>And to escape social death, we rely overwhelmingly on social media that pretends to be the solution or fix for (a mainly middle-class) sociability, on which (mainly empty) slogans of solidarity and empathy prevail. We are all in this together. But the means to escape social death truly actualise and normalise the unconscious desire to escape socialising. In collective withdrawal, indifference is shown to blue collar workers compelled to continue work in hazardous workplaces, while white collar workers remain comfortably indoors. The inside/outside trope which came to define intraworkplace dynamics and the character of some work, now defines the classification of work across the whole society.</p>
<p><br>The futurist Alvin Toffler was one of the foremost prognosticators of our stay-at-home society. Writing in 1980, he proclaimed:</p>
<p style="text-align: center;"><br>Today it takes an act of courage to suggest that our biggest factories and office<br>towers may, within our lifetimes, stand half empty, reduced to use as ghostly<br>warehouses or converted into living space. Yet this is precisely what the new<br>mode of production made possible: a return to the cottage industry on a new,<br>higher, electronic basis, and with it a new emphasis on the home as the center of<br>society.<sup id="link_82"><a href="#ref_82">82</a></sup></p>
<p><br>As it once was for the pre-industrial worker, it is increasingly becoming the case for the postindustrial worker&ndash; workplace and home are united. In this set-up, another Tofflerian concept triumphs&ndash; that of the prosumer, &ldquo;a progressive blurring of the lines that separates producer from consumer.&rdquo;<sup id="link_83"><a href="#ref_83">83</a></sup> But, rather than emerging as some form of decentralised production &lsquo;empowering&rsquo; consumers to customise products according to their preferences and tastes, in our electronic cottages we instead conspicuously produce cultural commodities in pursuit of sign values, through tweets and the like(s). Have a break, make a TikTok. What has become of our free time&ndash; that precious thing for which we would all trade work for, has itself become a kind of work, consisting of endless hours spent on social media consuming &lsquo;content&rsquo; and crafting the perfect public image. Yet, aware of its soul-destroying mindlessness, its stealthy clawing at the day, we overcompensate by working a bit more. Only work can liberate us from the disappointments of work. Escape from work only leads back to it. Escape from work is work.&nbsp;</p>
<p>The predicament of immeasurability now meets the walls of domestic privacy, and answers with increased surveillance. As recent writing shows, there has been a massive surge in the use of software technologies by employers designed to track and monitor employee activity.<sup id="link_84"><a href="#ref_84">84</a></sup> This time, perhaps, workers are more than usual alive to their bosses efforts to control the labour process, to exert power over every dimension of their lives.<sup id="link_85"><a href="#ref_85">85</a></sup> Not so much a realisation of having bullshit jobs&ndash; as unemployment soars globally, most feel fortunate to have a job at all&ndash; but of bullshit in jobs.<sup id="link_86"><a href="#ref_86">86</a></sup><br>What might become clearer (although probably not), is that alienation&ndash; that intrinsic condition of capitalist labour relations which requires employees to relinquish the right to control their labour&ndash;is what is expressed in objections to the organisation of work today, and not the notion of work itself.</p>
<p><br>That the COVID &ldquo;work from home&rdquo; regime represents the complete colonisation of work over life is obvious&ndash; what this means for resistance, less so. What hopes are there for collective action if the labour process is no longer spatio-temporally collectivised? Here once again the electronic cottage metaphor is apposite&ndash; for unlike labour carried out in the confines of a factory or office, labour today returns the worker to a mode where she is isolated when conducting her work, where she is, as it were, structurally disorganised.&nbsp;</p>
<p><br>Digital connectivity alone does not translate to collectivity. In fact, more often than not, it has the opposite effect. The ease/convenience of &lsquo;anytime&rsquo; access to others that connectivity provides, ensures our mutually-assured-isolation. Deprived of opportunities to establish interpersonal relationships with fellow employees who we may have once shared a space with, our relationships external to workplaces in the form of a series of business PR interactions accelerate. Friendships exist for the cameras&rsquo; gaze; fueling neoliberal individuation and competition &ndash; &ldquo;I am friends with you when the optics look good for me&rdquo;. Everything is precarious, everyone is a cancellation postponed. It is no coincidence that words like &lsquo;connections&rsquo; and &lsquo;network&rsquo; have proliferated in our social life lexicon. This type of online connectivity has not provided pathways for collectivity, but has rather subordinated social life as we know it to competitive self-marketing. We are all entreployees now.&nbsp;</p>
<p>Recently, the writer Sam Kriss eloquently described social media as &ldquo;a tool that possesses the man. Like the owner of property, but also like a possessing devil. It takes over your mouth and your hands, and it whispers right into your brain. It tells you that the people around you are enemies, that you might be an enemy; it sends you spiralling into the claustrophobia of yourself.&rdquo;<sup id="link_87"><a href="#ref_87">87</a></sup> On social media, relations between things appear as relations between men. The new subject of history is extremely online, a commodified self that must necessarily be narcissistic to ensure the viability of the online product which precedes and supersedes the true self, from whom the individual is disconnected.</p>
<p><br>Online resistance as we know it, serves so far only to co-ordinate subjects with the established reality of increased individuation, isolation and surveillance, and will continue to do so as long as digital platforms are designed to maximise the exploitation of the user for capitalist gain.<sup id="link_88"><a href="#ref_88">88</a></sup> The long-term solution (if there is one) can never be to substitute real collectivity for the realm of the virtual (even in a time of pandemic). But, it is clear that they are here to stay&ndash;and if digital platforms are able to facilitate some collectivity at all, there first needs to be a fundamental redesigning of the platforms that host our online lives. The fact that Facebook is developing workplace tools that could censor words like &lsquo;unionize&rsquo; should make this need very clear.<sup id="link_89"><a href="#ref_89">89</a></sup> But it is also what makes this prospect far from likely. How do you socialize the platform monopolies whose very existence arises from and perpetuates our anti-social society?</p>
<p><br>Perhaps this is to overstate the implications of a phenomenon that affects a specific kind of labourer, and particularly in this essay, the white collar worker. But there is a general, society-wide transformation in the making of which this all forms but a small part. Yes, as previously stated&ndash;Gramsci is evergreen, so much so that he is quoted by right-wing governments embracing (even if only fleetingly), state-led planning directives incurring public debt to finance responses to the COVID-19.<sup id="link_90"><a href="#ref_90">90</a></sup> Today, the crisis consists precisely in the fact that it is easier to imagine an end to capitalism than the arrival of socialism. At &ldquo;the end of the end of history,&rdquo; post-capitalism can no longer be equated with a socialist alternative. We are a society caught between the non-death of neoliberalism and the rise of neo-feudalism.<sup id="link_91"><a href="#ref_91">91</a></sup> What new weapons serve this terrain? Perhaps to look for new weapons is the mistake, to be convinced of the novelty of a situation which is the historical rule of any classed society.&nbsp;</p>
<p>In contemplating the condition of our working lives and living work, one must finally then ask&ndash;where is the working class?</p>
<p><br><a href="#link_81"><sup id="ref_81">81</sup></a> Lydia Kallipoliti, &ldquo;Zoom In, Zoom Out,&rdquo; E-Flux, 29 April 2020, <a href="https://www.e-flux.com/architecture/atthe-border/325754/zoom-in-zoom-out/" target="_blank">https://www.e-flux.com/architecture/atthe-border/325754/zoom-in-zoom-out/</a>.</p>
<p><a href="#link_82"><sup id="ref_82">82</sup></a> Alvin Toffler, The Third Wave (New York: Morrow, 1980), 194.</p>
<p><a href="#link_83"><sup id="ref_83">83</sup></a> Ibid., 267.</p>
<p><a href="#link_84"><sup id="ref_84">84</sup></a> Ben Burgis, &ldquo;Your Boss is Spying on You,&rdquo; Jacobin, 14 April 84 2020, <a href="https://www.jacobinmag.com/2020/04/worker-surveillance-work-from-home-employee-monitoring-software" target="_blank">https://www.jacobinmag.com/2020/04/worker-surveillance-work-from-home-employee-monitoring-software</a>.</p>
<p><a href="#link_85"><sup id="ref_85">85</sup></a> Emma Jacobs, &ldquo;Paranoia Creeps into Homeworking,&rdquo; The Financial Times, 18 June 2020,<a href="https://www.ft.com/content/e50ce245-09fd-4831-a90b-953ef51a2281" target="_blank"> https://www.ft.com/content/e50ce245-09fd-4831-a90b-953ef51a2281</a>.</p>
<p><a href="#link_86"><sup id="ref_86">86</sup></a> That neat turn of phrase is taken from Anton Jager: Doug Henwood, &ldquo;Laboring Under an Illusion, an Interview with Anton Jager,&rdquo; Jacobin, 27 December 2018, <a href="https://jacobinmag.com/2018/12/post-work-labor-ubi-coercion-capitalism" target="_blank">https://jacobinmag.com/2018/12/post-work-labor-ubi-coercion-capitalism</a>.</p>
<p><a href="#link_87"><sup id="ref_87">87</sup></a> Sam Kriss, &ldquo;White Skin, Black Squares&rdquo;, Idiot Joy Showland, 10 June 2020, <a href="https://samkriss.com/2020/06/10/white-skin-black-squares" target="_blank">https://samkriss.com/2020/06/10/white-skin-black-squares/</a></p>
<p><a href="#link_88"><sup id="ref_88">88</sup></a> Some, like Christian Fuchs have argued that the user-generated data produced through digital constitutes exploited surplus value. See for example: Christian Fuchs, Digital labour and Karl Marx (New York: Routledge, 2014).</p>
<p><a href="#link_89"><sup id="ref_89">89</sup></a> Lee Fang, &ldquo;Facebook Pitched New Tool Allowing Employers to Suppress Words Like &lsquo;Unionize&rsquo; In Workplace Chat Product,&rdquo; The Intercept, 12 June 2020, <a href="https://theintercept.com/2020/06/11/facebook-workplace-unionize/" target="_blank">https://theintercept.com/2020/06/11/facebook-workplace-unionize/</a></p>
<p><a href="#link_90"><sup id="ref_90">90</sup></a> Michael Gove, &ldquo;The Privilege of Public Service,&rdquo; Ditchley Annual Lecture, 1 July 2020, <a href="https://www.gov.uk/government/speeches/the-privilege-of-public-service-given-as-the-ditchley-annual-lecture" target="_blank">https://www.gov.uk/government/speeches/the-privilege-of-public-service-given-as-the-ditchley-annual-lecture</a>.</p>
<p><a href="#link_91"><sup id="ref_91">91</sup></a> Robert Kuttner and Katherine V. Stone, &ldquo;The Rise of Neo-Feudalism,&rdquo; The American Prospect, 8 April 2020, <a href="https://prospect.org/economy/rise-of-neo-feudalism/?fbclid=IwAR2spte-KfCLlUnmcGhwCJZgBb3mD85MbWJK4CJu1BRIb9lm2M5SXe9Zbkg" target="_blank">https://prospect.org/economy/rise-of-neo-feudalism/?fbclid=IwAR2spte-KfCLlUnmcGhwCJZgBb3mD85MbWJK4CJu1BRIb9lm2M5SXe9Zbkg</a>; Jodie Dean, &ldquo;Neofeudalism: The End of Capitalism?&rdquo; Los Angeles Review of Books, 12 May 2020, <a href="https://lareviewofbooks.org/article/neofeudalism-the-end-of-capitalism/" target="_blank">https://lareviewofbooks.org/article/neofeudalism-the-end-of-capitalism/</a>.</p>`